# Generated by Django 6.0.4 on 2026-04-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('media_type', models.CharField(choices=[('image', 'عکس'), ('audio', 'صوت'), ('video', 'فیلم')], max_length=10, verbose_name='نوع رسانه')),
                ('file', models.FileField(upload_to='media_files/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_app.mediacategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'فایل رسانه',
                'verbose_name_plural': 'فایل\u200cهای رسانه',
                'ordering': ['-created_at'],
            },
        ),
    ]
